"""Initial  migration

Revision ID: a0a9430bcf6b
Revises: 
Create Date: 2024-03-10 17:32:33.680834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a9430bcf6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('seatno', sa.Integer(), nullable=False),
    sa.Column('startstation', sa.String(length=120), nullable=False),
    sa.Column('endstation', sa.String(length=120), nullable=False),
    sa.Column('coachname', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('endstation'),
    sa.UniqueConstraint('seatno'),
    sa.UniqueConstraint('startstation'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
